### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by MulverineX** [Alex313031/thorium#564] opened 2024-02-20 08:11 UTC
**System Details**
 - OS: Windows 11 w/ Atlas playbook
 - Hardware: i7-10750H, 16GB memory, RTX 2070
 - Thorium Version 121.0.6167.204

**Problem**
After updating to 121 from 119 Thorium refused to run, and through the terminal I got simply `Segmentation Fault`.

Also a side note, to downgrade I had to download the release zip and replace manually, the mini installer wouldn't downgrade.

**Comment by gz83** [comment] 2024-02-20 08:33
I don't encounter this error, in which version did you encounter this error (AVX, AVX2 or SSE3)?

@MulverineX

**Comment by MulverineX** [comment] 2024-02-20 08:54
@gz83 I tried all 3 versions

**Comment by gz83** [comment] 2024-02-20 09:10
Please tell me the specific process of reproducing the problem and I will try to see if I can reproduce the problem you encountered.

@MulverineX

**Comment by MulverineX** [comment] 2024-02-20 09:56
- Have 119 installed
- Use https://github.com/Alex313031/thorium-winupdater/releases/tag/1.8.1
- Seg faults
- Unzip the BIN directory of any of the release types into your installation folder
- Seg faults regardless of type

**Comment by Alex313031** [comment] 2024-02-20 11:10
@MulverineX I tried all the versions in a Win 10 VM, and had no problems. Also @gz83 is using Win 11 too.

**Comment by MulverineX** [comment] 2024-02-20 11:16
Very strange, is there some way for me to get additional debug information?

**Comment by gz83** [comment] 2024-02-20 12:09
Skip winupdater and completely delete the original installed version, then install version 121 to see if you still encounter errors.

@MulverineX

**Comment by MulverineX** [comment] 2024-02-20 23:34
It appears that after restarting the computer and the update service running again, the browser is updated with no issues, very strange

**Comment by MulverineX** [comment] 2024-02-21 06:27
Aaaand it's broken again

**Comment by AnuRage-git** [comment] 2024-02-22 05:29
I've been getting the same Segmentation fault issue on Linux though. My Windows version works perfectly fine. Only issue is Netflix playback where it gets stuck in a clear cookies loop but it could be a Netflix issue too

**Comment by Yaakoss** [comment] 2024-02-25 11:02
The issue is caused by the profile manager. Thorium crashes if there are Profiles that have been added in the previous versions or if you add a new profile.
There is a workaround if you need multiple profiles.
You can create a new separate directory for each profile you use using the --user-data-dir parameter. At least on Linux this works.

**Comment by dmolin** [comment] 2024-02-25 11:06
@Yaakoss yes, I noticed. In particular, I noticed that the issue was located in the "Local State" file but I was unable to pinpoint what exact part of it triggers the core dump.
For the moment I'm back to Chromium, that work just fine using the copy of my thorium config folder as-is, with all my bookmarks, profiles etc in place

**Comment by ThatMarko** [comment] 2024-02-26 23:02
+1 for this error on latest KDE Neon (Ubuntu 22.04)

`thorium-browser
[603862:603862:0226/170154.952517:ERROR:policy_logger.cc(156)] :components/enterprise/browser/controller/chrome_browser_cloud_management_controller.cc(161) Cloud management controller initialization aborted as CBCM is not enabled. Please use the `--enable-chrome-browser-cloud-management` command line flag to enable it if you are not using the official Google Chrome build.
[0226/170154.985916:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[0226/170154.986036:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[0226/170154.987524:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[0226/170154.988580:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[0226/170154.991592:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[0226/170154.991652:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[0226/170154.992615:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[1]    603862 segmentation fault (core dumped)  thorium-browser

`

**Comment by federerfanatic** [comment] 2024-02-27 13:22
Version 21.0.6167.204-1 on Ubuntu-22.04 does not start up and segments. 

inxi -G
Graphics:
  Device-1: Intel CoffeeLake-S GT2 [UHD Graphics 630] driver: i915 v: kernel
  Device-2: NVIDIA GP106 [GeForce GTX 1060 6GB] driver: nvidia
    v: 535.154.05
  Display: x11 server: X.Org v: 1.21.1.4 driver: X:
    loaded: modesetting,nvidia gpu: i915,nvidia resolution: 5120x1440~70Hz
  OpenGL: renderer: NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2

CPU: 6-core Intel Core i5-9400 (-MCP-) speed/min/max: 3769/800/4100 MHz
Kernel: 5.15.0-97-generic x86_64 Up: 39m Mem: 38919.6/64151.6 MiB (60.7%)


thorium-browser 
[118097:118097:0227/080057.596472:ERROR:policy_logger.cc(156)] :components/enterprise/browser/controller/chrome_browser_cloud_management_controller.cc(161) Cloud management controller initialization aborted as CBCM is not enabled. Please use the `--enable-chrome-browser-cloud-management` command line flag to enable it if you are not using the official Google Chrome build.
[118097:118097:0227/080057.624910:ERROR:content_settings_pref.cc(311)] Invalid pattern strings: http://i%20reported%20a%20few%20days%20ago%20about%20a%20new%20state-of-the-art,%20open-source%20model%20that%20outperforms%20all%20other%20models,%20including%20gpt-4.%20this%20model%20is%20sqlcoder-70b.%20in%20a%20nutshell,%20based%20on%20meta's%20recent%20codellama-70b,%20defog%20leveraged%20its%20own%20hand-crafted%20dataset%20and%20built%20a%20new,%20fine-tuned%20model:80,*
[118097:118097:0227/080057.632215:ERROR:content_settings_pref.cc(311)] Invalid pattern strings: http://[*.]%20this%20model%20is%20sqlcoder-70b.%20in%20a%20nutshell,%20based%20on%20meta's%20recent%20codellama-70b,%20defog%20leveraged%20its%20own%20hand-crafted%20dataset%20and%20built%20a%20new,%20fine-tuned%20model,*
[0227/080058.008713:ERROR:elf_dynamic_array_reader.h(64)] tag not found
Segmentation fault (core dumped)

**Comment by federerfanatic** [comment] 2024-02-27 13:23
I downgraded to version 120.0.6099.235-1 and used apt-mark to hold it.

**Comment by sf-sahil-jassal** [comment] 2024-03-01 05:48
I also downgrade to v120 also, as Thorium was complaining about Segmentation fault while creating new profile.

**Comment by federerfanatic** [comment] 2024-03-01 14:44
> I downgraded to version 120.0.6099.235-1 and used apt-mark to hold it.

Ok. I now have installed the latest version. I was having problems with the nvidia driver. Advice: reboot machine
and do not pick the special options menu item in the boot menu. Just boot normally. I had installed the kernel headers files during the boot process as the desktop was not coming up. It came as the build was finishing but I neglected to reboot from scratch. If nvtop can not access the gpu despite the desktop being supposely running then you really should reboot.

**Comment by federerfanatic** [comment] 2024-03-01 14:45
The latest version 121.0.6167.204-1 works on ubuntu-22.04 amd 64 running Xorg.

**Comment by daggerwolf45** [comment] 2024-03-02 17:26
I have the same issue. I'm on Arch running Linux 6.7.6. Downgrading to 120.0.6099.235-1 fixed it for me as well.

**Comment by mindrunner** [comment] 2024-03-03 15:24
I can work around this issue by selecting a user profile on startup (skipping the profile manager)

`
thorium-browser --profile-directory=Default
`

**Comment by Alex313031** [comment] 2024-03-15 00:23
@MarceloEmmerich @dmolin @mindrunner @ThatMarko @MulverineX Fixed in latest M122 version.

**Closed by Alex313031** 2024-03-15 00:23 UTC
