### ISSUE TITLE
JPEG-XL support post M109

### ISSUE THREAD

**Issue by goodusername123** [Alex313031/thorium#104] opened 2023-02-04 13:53 UTC
Is it planned to support JXL files after M109? it seems like a reversion patch could be made for [this commit](https://chromium.googlesource.com/chromium/src/+/166a9f3c512fb7806324af7b4fdd85bee0cde149) to restore support.

websites that that I currently know of that are shipping JXL files include the majority if not all sites using/made with [Shopify](https://www.shopify.com/) (of which there is [quite a bit](https://www.aftership.com/store-list/top-100-shopify-stores)) and also the gallery pages on a [personal site made by a artist and photographer](https://saklistudio.com/)

also it seems like some of the chromium devs responsible for the original implementation are willing to provide support if stuff ends up breaking in future chromium milestones.

one of the reasons for me asking if continued support is planned is so I can know whether or not I can confidently recommend people over to Thorium as a alternative chromium fork that keeps JXL support post M109 and also to know if maybe it is eligible to be added to [this list](https://github.com/libjxl/libjxl/blob/main/doc/software_support.md).

(edit) here are some websites that can be used to test JXL support listed below:
- https://jpegxl.info/test-page
- https://saklistudio.com/jxltests/
- https://people.csail.mit.edu/ericchan/hdr/hdr-jxl.php

**Comment by goodusername123** [comment] 2023-02-04 16:24
I should mention that if a patch is created it's recommended to edit the "DEPS" file and change

`  'libjxl_revision': '8001738dc9cd8dc6fa24cf75fefd08f909b2ac3c',`
to
`  'libjxl_revision': 'c27d499263435ac77007174e0f1cf54557cff23a',`

and

`  'highway_revision': '8ae5b88670fb918f815b717c7c13d38a9b0eb4bb',`
to
`  'highway_revision': '58746ca5b9f9444a2a3549704602ecc6239f8f41',`


which should result in libjxl getting updated from 0.7.0rc to 0.8.1 and highway (which is required by libjxl) getting updated from 1.0.1rc to 1.0.3 hopefully.

**Comment by jonsneyers** [comment] 2023-02-13 07:58
It would be good to know if JPEG XL support will remain in Thorium after M109. I'm certainly hoping @Alex313031 can confirm this intention, since Thorium is currently the only browser with full JPEG XL support including HDR — HDR does not work properly in the four other browsers that currently have JPEG XL enabled by default, since they're all Firefox forks and Firefox doesn't support HDR in general. So for use cases like [this one](https://helpx.adobe.com/in/camera-raw/using/hdr-output.html) currently Thorium is the only option.

**Comment by jonsneyers** [comment] 2023-02-13 15:33
What can we do to reduce development pressure?

Would it help if we (libjxl devs) maintain an up-to-date chromium patch for jxl somewhere (e.g. on the chromium gerrit itself)?

**Comment by midzer** [comment] 2023-02-13 16:04
After watching talk https://www.youtube.com/watch?v=RYJf7kelYQQ from @jonsneyers I am certainly in favor of supporting JPEG XL long term in Thorium.

Until now, I've not heard of it's main features like "Responsive by design" and "Legacy friendly". Not checking compression ratios on my own and relying on the graph shown in the video, I think JPEG XL's approach is the way to go for the web to replace ancient JPEG.

**Comment by mo271** [comment] 2023-02-14 13:43
I will try to see if I can keep an up-to-date rebased version of libjxl in chrome on https://chromium-review.googlesource.com/ and let you know if this is done.

**Comment by Alex313031** [comment] 2023-02-15 00:24
@mo271 @jonsneyers This is amazing that you guys are even here, lol. After talking with @gz83 and seeing @midzer excitement, and the fact that as @jonsneyers pointed out, thorium is currently the only browser with full jpeg-xl support, I want to make it an official goal to keep libjxl post M109. If one of you could make a patch, whether on gerrit or elsewhere, that would be really awesome!

@gz83 What milestone are you building at, and did you rebase anything. That build.gn is a file thorium uses.

**Comment by mo271** [comment] 2023-02-15 16:11
I was able to build the following commit locally:
https://chromium-review.googlesource.com/c/chromium/src/+/4255409/

This is a commit on top of current origin/main of chromium. It uses the last libjxl that was in chrome together with the libhighway that is currently in chromium (it had been updated in between..)

**Comment by mo271** [comment] 2023-02-16 13:42
I patched it a bit, since for one file the merge was botched. Should work better now. There are still some failing tests, probably due to the highway update, which I will fix when I find the time

**Comment by mo271** [comment] 2023-02-22 16:34
> @mo271
> 
> Moritz, I now compile libjxl files with Thorium's files. I encountered these problems in the process of compilation. Please check the following questions when you are free.
> 
> 1. The `version.h` header file introduced in `src/lib/include/jxl/decode.h` cannot be found during compilation, which causes compilation interruption
> 2. The following errors occur in `src/lib/include/jxl/decode.h`, causing compilation interruption
>    error: unknown type name 'jxlbitDepth'
>    JXLDECODERSETIMAGEOUTBITDEPTH (JXLDECODER* DEC, Const JXLBITDEPTH* bit_depth);
> 
> I have deleted the header file and code mentioned above, and compiled no longer report errors.

I haven't look into it in details, but perhaps that decode.h file is generated dynamically depending on how you build it?! 
The second error (and probably also the first?) sounds a bit like you are building with a version of libjxl that is to new. For now I would try building with the exact version that is referenced in my chromium patch. I will try to update libjxl to version 0.8.1 sometimes.

**Comment by Alex313031** [comment] 2023-02-27 15:51
@ziemek99 @tomByrer

**Comment by Alex313031** [comment] 2023-03-02 09:00
@mo271 @midzer @jonsneyers @gz83 @goodusername123 Thorium M110 is out, with full jpeg-xl support! (And it is built with libjxl 8.0, instead of 7.2) > https://github.com/Alex313031/Thorium/releases/tag/M110.0.5481.178

**Comment by Daasin** [comment] 2023-03-04 16:20
This would make Thorium my default browser instantly

**Comment by Alex313031** [comment] 2023-03-04 18:42
@Daasin I plan on making a new android build soon.

**Comment by Alex313031** [comment] 2023-03-29 11:00
@mo271 @midzer @jonsneyers @gz83 Thorium now has libjxl in M110 and M111, and will continue to have it for as long as we can keep the patches working. If noone else has anything else to comment, I will be closing this issue in a few days.

**Comment by Alex313031** [comment] 2023-05-03 13:32
@mo271 @midzer @jonsneyers @goodusername123 @yochananmarqos Thorium M112 still has working jpeg xl support.

For thorium 113 I would like to update libhighway to the non rc version of 1.0.3
and jibjxl to > https://github.com/libjxl/libjxl/commit/6ae7cffd78eff8edc0df6f2a5ee23e43b31ab947 
@mo271 @jonsneyers Are there any things that stand out or that you know of between https://github.com/libjxl/libjxl/commit/c27d499263435ac77007174e0f1cf54557cff23a and this revision as far as integration into chromium is concerned

**Comment by Alex313031** [comment] 2024-02-14 09:34
@mo271 @jonsneyers @gz83 @goodusername123 @Daasin libhighway was updated to 1.0.7, and libjxl was updated to 0.9.2 in the latest M121 release. It works well, however, something else in Thorium's code is causing segfaults, and I am working on it now before we build releases.
When it is done, maybe someone could test the HDR compliance, as some people said images were too bright.

**Comment by Firepal** [comment] 2024-02-24 14:17
Is JPEG XL supposed to work on an Android build of Thorium? arm64 M121 build doesn't display JPEG XL images for me.

**Comment by gz83** [comment] 2024-02-24 14:48
> Is JPEG XL supposed to work on an Android build of Thorium? arm64 M121 build doesn't display JPEG XL images for me.

Already in the to-do list

@Firepal

**Closed** 2024-09-02 05:45 UTC
