### ISSUE TITLE
add more furry

### ISSUE THREAD

**Issue by archuser114514** [Alex313031/thorium#474] opened 2023-12-18 09:34 UTC

**Comment by ysomad** [comment] 2023-12-18 11:24
based issue

**Comment by Alex313031** [comment] 2023-12-18 11:47
@ysomad @admiraldaro @archuser114514 They didn't kill it. Just damaged, and having lots of people leave.

**Comment by ysomad** [comment] 2023-12-18 16:41
Ikr, keep using it myself!

**Comment by BillBlight** [comment] 2023-12-18 19:37
Mistakes may have been made, but as for the furry stuff, but some people need to get a prescription to prozac or just drink heavily and realize that somethings for others are just not for them, and move on ..

Still going to keep using Thorium ...

**Comment by RadegasTCZ** [comment] 2023-12-18 20:24
Ye, the thing is you have to be careful about what you put on the internet. That's why I don't use X/Twitter pretty much at all and reddit pretty much the same, only if I am looking for something technical.

I personally don't insult people by those things. I am at the politics, something like "they have their thing, I have my thing".

I found this project when I was looking for something worth running under Win7 I recently installed for walkie-talkie things, gets the job done. I was considering an uninstall, but. That thing is mostly unused and I only connected it to guest network anyways.

Personally what am I against is people attacking the dev even going through the trouble of finding a phone number, recording calls and posting it publicly, because of silly things in someone's project that has a real purpose. This is not the way.

**Comment by jasonbrown1965** [comment] 2023-12-19 01:41
A human with fetishes?
Who, may I ask, has not seen the later afternoon sun, golden, strike an ankle in a certain way and not made us think for a fleeting moment .. mm

Wut?
WTF is this even doing on here?
Long before this nonsense, I went on the dev's profile link to a personal page and found a strikingly human response to a deeply abhorrent aspect of human nature, and no, it wasn't an adult fetish. I went looking because the browser was whiplash good and I was intrigued to know more, like, what else they were doing, dev or whatev. 

Nothing about furry porn. 
Dox kiddies may want to take a relook and retarget on a real problem like the dev does in their own personal life, i.e. exposing child abusers. 

Including dox kiddies led and misled by child abusers who orchestrate campaigns to target victims who speak out publicly, along with witnesses, whistleblowers, researchers and investigators. 

Dox them, not devs.

**Comment by jasonbrown1965** [comment] 2023-12-19 01:42
> based issue

Found the nine year old.

**Comment by ysomad** [comment] 2023-12-19 07:30
chill dude, it's just irony

**Comment by NextWork123** [comment] 2023-12-19 09:09
> @ysomad @admiraldaro @archuser114514 They didn't kill it. Just damaged, and having lots of people leave.

so much people gonna leave because the actions can have some consequences.  I used too thorium but i leave that and i'm sorry but i don't like your actions.

**Comment by DoruDoLasu** [comment] 2023-12-19 16:33
man, people sure are overreacting, I have never used this browser and now I keep hearing about this "dark side of open source" but the dark side I'm seeing is someone calling guy's phone over this, amount of misinformation that's been spread and perhaps worse things I don't know about

alright, the stuff on the chromium history section of the thorium website was legit awful and I have a feeling at least a few people just wanting to learn about some things and unwilling to witness an **actual furry porn drawing** clicked that not-really-descriptive link during the _few months_ it was up for and I can really understand people being mad about that, even if this version ended up committed accidentally you gotta have some responsibility for what you're hosting.

that archive of a website unrelated to browsers I will not comment on because just from the name alone I knew it's something I *do not* want to look at nor any photos depicting graphic content so I didn't, but from the url it didn't look like it was near the browser itself at least

however - the only *preinstalled furry porn* that actually was in this browser, that people are uninstalling it for, was just one drawing.
on the main version - one female furry character, with hands on her behind that's pointed at the viewer, looking back at the camera smiling, can make out some shapes through a bit slim underwear but granted some clothing is there.
not as bad as I thought, seen similar things on TV (anyone remembers that transformers movie?), though the win7 version lets you see an uncovered breast (oh the horrors) and it's not even furry (catgirls don't count, even if they're opening a fridge...)
none on the xp one... not sure if it's a good or bad thing
none on the firefox ones too disproving that it's a furry browser
the other chromium-based forks have more explicit stuff... yeah you should've definitely ask users of Atom-ng if they're over 18, while still no intercourses going on there's no clothing left for me to try excusing it.

joking a bit here, but it's really not a responsible thing to put "spicy stuff" in software if it's intended to be used by everyone, especially without clear warnings (if there were any, this could've went better). on the other hand it also doesn't really make a big difference if you're just using the browser and not hunting for secrets so not uninstalling it because of this doesn't make anyone a degenerate
but still.
if you're trying to appear professional and meanwhile you put this in, don't blame people for losing trust.
it can be regained, it's not like one dumbest idea that was removed after the people spoke up against it makes the code part bad (no need to make unyiffed-thorium fork) 
and at least it's not as bad of a situation as Pale Moon had (MyPal really didn't deserve it)

and it's also a bit of a lesson for everyone to at least skim through the sources of the little niche open source projects you might want to use because they might not be as innocent as you think...

**Comment by DoruDoLasu** [comment] 2023-12-19 16:36
Alright now that everything obvious is addressed there's also an important point that I have not seen anyone touch:
Did the authors of the artwork used in these easter eggs knew about it huh?
Have they allowed you to use it in your project? What is their license? Where is their credit?
I have a feeling that might not be the case with copyrighted characters in some of it...
So yeah next time you do an easter egg like that actually commission an artist to draw something and maybe even make it Thorium related.
You won't. You've probably learnt your lesson.
...but I've gave thumbs up for adding more furry, it doesn't have to be sexual and everyone keeps forgetting that.

**Comment by fernandofig** [comment] 2023-12-20 20:11
I'm sorry, but I think people here that are suddenly rushing to the defensive are miscontruing what's the reasoning behind poeple either leaving or giving a side eye to this project; or at least the reasoning for the "grown-ups" to be doing that - there were a lot of childish and abusive behavior on that other thread, which is a shame and absolutely not justifiable.

Even if they aren't agreeable to me, objectively I couldn't care less about Alex's (or anyone else's here) tastes in porn or intactivism ideas, as long as it's kept private, as it should. The problem is that nowadays a browser is a central part of almost everyone everyday life, and hence it having to be free of sensitive content speaks to the reliability of the browser and the project as a whole. Something as essential as web browser needs to be maintained with professionalism. When sensitive stuff is hidden in the browser, even as a joke, it creates a trust issue. Even if it's mostly harmless, it makes one wonder what else could be hidden, and what if it isn't as harmless as furries?

This is all compounded by the fact that this project is pretty much a one-man show, which is unsustainable in the long run. If this project is to survive and see actual growth and get over this debacle, it needs an infusion of professiolism, more contributors, and a structure for contribution that doesn't rely on gatekeeping it all on one person.

**Comment by diegosandovalramirez** [comment] 2023-12-21 16:21
what are all these nerds overreacting to? shit is funny, the internet is not the living room of your house

**Comment by ysomad** [comment] 2023-12-21 17:26
@diegosandovalramirez true, people not understanding irony enjoys drama

**Comment by FriskTheFallenHuman** [comment] 2023-12-22 02:28
I Really don't care tbh, this browser looks interesting even for a outsider like me, i would care if it was an actual spyware or virus, also the way you find that easter egg is like not to hard but is hard for your promedian user that doesn't know what chrome:\\ at the does, even for a kid so 🤷

**Comment by Synkstar** [comment] 2023-12-22 02:46
Relating to this issue: Its a web browser so you can look at whatever you want as much as you want. 

On git you can technically remove the history of this stuff entirely and not show any commits related to it and then just force push it if you want. But the people know about it and can find it on the web archive etc. 

This technically isn't even real yiff because it doesn't even show anything though lol

**Comment by xyz-864** [comment] 2023-12-22 07:28
all above trannies and 'cord groomers 
(typical of freetards)

**Comment by xyz-864** [comment] 2023-12-22 07:29
of course groomer trannies would want more furry porn in their freeslop...

**Comment by xyz-864** [comment] 2023-12-22 07:31
of course trannies want more furry pornography on their shitty little opensourceslop program

**Comment by xyz-864** [comment] 2023-12-22 08:03
fucking kill yourselves you porn addicted losers

**Comment by DRAGONTOS** [comment] 2023-12-22 10:02
The issue I encountered is not limited to just this repository (though you have addressed it here, which is appreciated). Unfortunately, it extends to several others as well, which complicates the situation.

**Closed** 2023-12-22 12:37 UTC
