### ISSUE TITLE
Red background  in side panel and Refresh UI not working

### ISSUE THREAD

**Issue by divyam234** [Alex313031/thorium#678] opened 2024-05-17 13:57 UTC
**System Details**
 - OS: Windows 11
 - Thorium Latest

I am seeing awful red background in side panel.

![image](https://github.com/Alex313031/thorium/assets/47589864/cc494ad2-9fa6-4c14-8a73-d3b758403afb)

**Comment by Nicols0Mart** [comment] 2024-05-17 14:12
Having the same issue here. Also using win11 and todays build. 
I know is not related to the issue, but in latest build I can't manage to enable chrome refresh 2023 UI. If someone facing the same issue let me know I'll open a separate issue for it

**Comment by divyam234** [comment] 2024-05-17 14:16
@Nicols0Mart  Can confirm chrome refresh 2023 not working for me also

**Comment by krystofkrticka** [comment] 2024-05-17 14:33
I'm also having this issue. Call me weird but I actually like how the 2023 redesign looks 😆

**Comment by Ciancy28** [comment] 2024-05-17 14:35
> I'm also having this issue. Call me weird but I actually like how the 2023 redesign looks 😆

same

**Comment by firegold763** [comment] 2024-05-17 15:45
It's a common issue in M124, since Google is deprecating the old layout in favour of the new insanely huge Chrome Refresh (that has the greatest thing of having scroll arrows in context menus on every screen that has a lower resolution of 4K or has a scaling that is higher than 100%, usually laptops) bullshit. That's why I'm still in M123 which is the last version that has the fully working old layout, I hope this will be fixed at least on Thorium.

**Comment by Alex313031** [comment] 2024-05-17 21:43
@krystofkrticka @divyam234 @Ciancy28 @Nicols0Mart @firegold763 I can confirm the red issue, however, read the release notes about how to get Chrome Refresh 2023 UI working properly.

**Comment by firegold763** [comment] 2024-05-17 21:51
> @krystofkrticka @divyam234 @Ciancy28 @Nicols0Mart @firegold763 I can confirm the red issue, however, read the release notes about how to get Chrome Refresh 2023 UI working properly.

I've added that command line in the shortcut, but the red background is still there. Maybe I'm doing something wrong.

**Comment by Ciancy28** [comment] 2024-05-17 21:57
> @krystofkrticka @divyam234 @Ciancy28 @Nicols0Mart @firegold763 I can confirm the red issue, however, read the release notes about how to get Chrome Refresh 2023 UI working properly.

well, it looks like #customize-chrome-side-panel was automatically reset to default after this update (I had enabled it in the previous release as explained by m123 release notes), re-enabling it did fix the issue for me, but that wasn't mentioned anywhere in the m124 release notes, unless I missed something despite reading the whole thing multiple times

**Comment by krystofkrticka** [comment] 2024-05-18 08:01
I tried multiple times re-enabling it but I still got the old design. This looks like the bug which happened to me in production version of chrome, that on some computers it was working just fine but on some it still shown the old design, before it was forced on all users and is working just fine on all computers.

**Comment by krystofkrticka** [comment] 2024-05-18 08:06
But in apps using electron which is based on chromium it is quite annoying because there are the context menus stupidly large. Though in chrome I don't mind it, maybe that is that I have all my computers set with scaling to 100% and was using MS Edge (also based on chromium) for a while which got those thicc context menus first, and if I compare it with chrome it looks like chrome has still quite normal size of those context menus compered to MS edge.

**Comment by Ciancy28** [comment] 2024-05-20 22:36
> > @krystofkrticka @divyam234 @Ciancy28 @Nicols0Mart @firegold763 I can confirm the red issue, however, read the release notes about how to get Chrome Refresh 2023 UI working properly.
> 
> well, it looks like #customize-chrome-side-panel was automatically reset to default after this update (I had enabled it in the previous release as explained by m123 release notes), re-enabling it did fix the issue for me, but that wasn't mentioned anywhere in the m124 release notes, unless I missed something despite reading the whole thing multiple times

unfortunately, today my thorium install suddenly reverted back to non-refresh 2023 ui and re-enabling the flag doesn't fix it anymore

**Comment by krystofkrticka** [comment] 2024-05-21 06:34
> > > @krystofkrticka @divyam234 @Ciancy28 @Nicols0Mart @firegold763 I can confirm the red issue, however, read the release notes about how to get Chrome Refresh 2023 UI working properly.
> > 
> > 
> > well, it looks like #customize-chrome-side-panel was automatically reset to default after this update (I had enabled it in the previous release as explained by m123 release notes), re-enabling it did fix the issue for me, but that wasn't mentioned anywhere in the m124 release notes, unless I missed something despite reading the whole thing multiple times
> 
> unfortunately, today my thorium install suddenly reverted back to non-refresh 2023 ui and re-enabling the flag doesn't fix it anymore

yep, this looks like the issue I had with Chrome before the refresh was released and that was that refresh was working on some computers and on some didn't

**Comment by Frimac07** [comment] 2024-05-22 12:42
I am on Debian and facing the same issue

**Comment by linehaulai** [comment] 2024-05-28 03:20
> @krystofkrticka @divyam234 @Ciancy28 @Nicols0Mart @firegold763 I can confirm the red issue, however, read the release notes about how to get Chrome Refresh 2023 UI working properly.

I read through your notes, and followed the instructions to patch this, but am hung up at the end.
What exactly is the syntax that needs to be written in terminal to get remove the red GUI from the side panel?
I work exclusively out ot of that panel, and if I can't resolve this, I'm going to have to sit the rest of this release out.

**Comment by Alex313031** [comment] 2024-09-03 08:24
@krystofkrticka @divyam234 @Nicols0Mart @Ciancy28 @gz83 @fakebizprez @firegold763 Closing this since M126 and beyond will no longer have this issue.

**Closed as completed by Alex313031** 2024-09-03 08:24 UTC
