### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by strangetheproot** [Alex313031/thorium#570] opened 2024-02-21 12:07 UTC
**System Details**
 - OS: Arch Linux 
 - Thorium Version: 121.0.6167.204

**Problem**
Upgraded from Thorium 120 to 121 and crashes after I launch, launching from Terminal, I get the Segmentation fault error. Any fixes?

**Comment by mathisen99** [comment] 2024-02-21 19:09
I got same issue.
Also on Arch and same version.

**Comment by AnuRage-git** [comment] 2024-02-22 05:27
Yes. I've been getting the same issue since the last two days
OS : EndeavourOS
WM : Hyprland

**Comment by ms178** [comment] 2024-02-22 11:42
I am on CachyOS, but see no issues with Thorium 121, but I've also compiled BoringSSL-git and quite a lot of other packages myself. I can't tell if that makes a difference.

**Comment by Yaakoss** [comment] 2024-02-23 08:14
Eventuially the same issue as in https://github.com/Alex313031/thorium/issues/564

OS: Arch Linux 6.7.5-arch1-1
WM: Qtile 0.24.0-2
running on Xorg

```
thorium-browser --enable-chrome-browser-cloud-management--enable-chrome-browser-cloud-management
The fastest browser on Earth.

(thorium-browser:89272): Gtk-WARNING **: 09:11:31.935: Theme parsing error: gtk.css:7852:22: Expected '(' after 'url'

(thorium-browser:89272): Gtk-WARNING **: 09:11:31.935: Theme parsing error: gtk.css:7852:147: Invalid character in string. Must be escaped.

(thorium-browser:89272): Gtk-WARNING **: 09:11:31.939: Theme parsing error: gtk.css:11635:3: '/*' in comment block

(thorium-browser:89272): Gtk-WARNING **: 09:11:31.939: Theme parsing error: gtk.css:11741:2: '/*' in comment block

(thorium-browser:89272): Gtk-WARNING **: 09:11:31.939: Theme parsing error: gtk.css:11786:26: 'text-shadow' is not a valid color name

(thorium-browser:89272): Gtk-WARNING **: 09:11:31.939: Theme parsing error: gtk.css:12048:14: 'ffffff' is not a valid color name
[89272:89272:0223/091131.990050:ERROR:atom_cache.cc(224)] Add _ICC_PROFILE_1 to kAtomsToCache
[89272:89272:0223/091131.990314:ERROR:atom_cache.cc(224)] Add _ICC_PROFILE_2 to kAtomsToCache
[0223/091132.033736:ERROR:elf_dynamic_array_reader.h(64)] tag not found
Segmentation fault (core dumped)
```
Coredump (the last part)
```
warning: Can't open file /SYSV00000000 (deleted) during file-backed mapping note processing

warning: Can't open file /dev/shm/.org.chromium.Chromium.GaKN7E (deleted) during file-backed mapping note processing

warning: Can't open file /dev/shm/.org.chromium.Chromium.BTxzFZ (deleted) during file-backed mapping note processing

warning: Can't open file /dev/shm/.org.chromium.Chromium.JSwpfi (deleted) during file-backed mapping note processing

warning: Can't open file /dev/shm/.org.chromium.Chromium.a5Exmv (deleted) during file-backed mapping note processing

warning: Can't open file /dev/shm/.org.chromium.Chromium.iRVjEZ (deleted) during file-backed mapping note processing

warning: Can't open file /dev/shm/.org.chromium.Chromium.D31wnn (deleted) during file-backed mapping note processing

warning: Can't open file /dev/shm/.org.chromium.Chromium.AgbpE9 (deleted) during file-backed mapping note processing

warning: Can't open file /dev/shm/.org.chromium.Chromium.u3x0V1 (deleted) during file-backed mapping note processing

warning: Can't open file /dev/shm/.org.chromium.Chromium.5IDamX (deleted) during file-backed mapping note processing

warning: Can't open file /dev/shm/.org.chromium.Chromium.pU5M1t (deleted) during file-backed mapping note processing
[New LWP 83307]
[New LWP 83321]
[New LWP 83328]
[New LWP 83335]
[New LWP 83329]
[New LWP 83340]
[New LWP 83330]
[New LWP 83332]
[New LWP 83347]
[New LWP 83344]
[New LWP 83331]
[New LWP 83342]
[New LWP 83333]
[New LWP 83345]
[New LWP 83353]
[New LWP 83327]
[New LWP 83337]
[New LWP 83339]
[New LWP 83357]
[New LWP 83355]
[New LWP 83338]
[New LWP 83348]
[New LWP 83367]
[New LWP 83343]
[New LWP 83349]
[New LWP 83356]
[New LWP 83346]
[New LWP 83336]
[New LWP 83358]
[New LWP 83359]
[New LWP 83334]
--Type <RET> for more, q to quit, c to continue without paging--
Downloading separate debug info for /opt/thorium-browser/libffmpeg.so
Downloading separate debug info for /usr/lib/libcairo.so.2
--Type <RET> for more, q to quit, c to continue without paging--
Downloading separate debug info for /usr/lib/libunistring.so.5
Downloading separate debug info for /usr/lib/libtasn1.so.6
Downloading separate debug info for /usr/lib/libcairo-gobject.so.2
Downloading separate debug info for system-supplied DSO at 0x7ffe88f87000
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Core was generated by `/opt/thorium-browser/thorium --enable-chrome-browser-cloud-management         .'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00005a10311fd2c4 in ?? ()
[Current thread is 1 (Thread 0x762efcba4240 (LWP 83307))]
```

**Comment by xiota** [comment] 2024-02-23 08:30
> My CPU has to use the SSE3 build, I tried the SSE3 version, but I still got the Segmentation Fault.

I suspect... A file mixup?  Suppose an AVX version was uploaded with an SSE3 filename... Might cause problems.

**Comment by Yaakoss** [comment] 2024-02-23 08:41
my CPU supports sse4.1/4.2 and avx2.

**Comment by gz83** [comment] 2024-02-23 08:45
This commit should fix crashes and bugs, but won't take effect until version 122

https://github.com/Alex313031/thorium/commit/5373a94bf0e367529c5b9fb5dd07044fb341eba9

**Comment by xiota** [comment] 2024-02-23 08:48
> This commit should fix crashes and bugs, but won't take effect until version 122 ... 5373a94bf0e367529c5b9fb5dd07044fb341eba9

Does that mean... removing the profile directory and starting with a fresh profile could prevent the segfault?

**Comment by gz83** [comment] 2024-02-23 08:52
> > This commit should fix crashes and bugs, but won't take effect until version 122 ... [5373a94](https://github.com/Alex313031/thorium/commit/5373a94bf0e367529c5b9fb5dd07044fb341eba9)
> 
> Does that mean... removing the profile directory and starting with a fresh profile could prevent the segfault?

It is currently recommended not to use the new user profile function until the next version is released.

@xiota

**Comment by Yaakoss** [comment] 2024-02-23 08:59
I can confirm. renamed .cache/thorium and created a new one. Thorium starts then. As soon as i create a new profile the browser crashes with elf_dynamic_array_reader.h(64)] tag not found.

**Comment by xiota** [comment] 2024-02-23 09:01
@Yaakoss Do you think 121.0.6167.204 should be blacklisted in the aur package?

**Comment by Yaakoss** [comment] 2024-02-23 09:12
@xiota 
i don't know. It might be better not to blacklist the package but add the note that it does not seem to work with multiple profiles. 

As for me Thorium is not the only browser i use in my system. I can recreate the second Profile in brave.

**Comment by MrGamerDoesGames** [comment] 2024-02-24 04:18
Sucks to hear that it's just broken, I use separate profiles extensively. It was a huge selling point for me. (one profile for school, another for personal)

**Comment by gz83** [comment] 2024-02-25 02:29
Follow up #564

**Comment by Alex313031** [comment] 2024-03-15 00:25
@mathisen99 @midzer @xiota @ms178 @MrGamerDoesGames Fixed in latest M122 version.

**Comment by MrGamerDoesGames** [comment] 2024-03-15 00:25
> @mathisen99 @midzer @xiota @ms178 @MrGamerDoesGames Fixed in latest M122 version.

Good work, thank you!

**Closed by Alex313031** 2024-03-15 00:25 UTC
